### ISSUE TITLE
views

### ISSUE THREAD

**Issue by Bryandumpit** [KeeveRW11/giglr#7]
* search function (fetch from Giphy API)
* handlebars:
  * layout: main
  * homepage
  * login
  * single-post
  * edit-post
  * create user 
  * dashboard
partials:
  comments
  post-info

* CSS (bootstrap)
* frontend javascript

**Comment by maheshramdas** [comment]
Hi Bryan,

I see #7 issue assigned to me. Could please let me know which one from the
below list is the one I need to work on?

-

search function (fetch from Giphy API)
-

handlebars:

   - layout: main
   - homepage
   - login
   - single-post
   - edit-post
   - create user
   - dashboard
   partials:
   comments
   post-info

-

CSS (bootstrap)
-

frontend javascript
- Br,
- Mahesh Ramdas
